version: "3"

services:
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
  notebook:
    build: ./notebook
    ports:
      - "8888:8888"
    links:
      - mongo
    environment:
      - GRANT_SUDO=yes
    user:
      - root


